version: 2.1

executors:
  base-agent:
    docker:
      - image: twdps/di-circleci-infra-image:stable

jobs:
  validate-secret-patterns:
    executor: base-agent
    steps:
      - checkout
      - run: bats test

  scan-repos-for-secrets:
    executor: base-agent
    steps:
      - checkout
      - run: ./scan_repo_for_secrets.sh

workflows:
  version: 2
  main:
    jobs:
      - validate-secret-patterns

  scan-secrets:
    jobs:
      - scan-repos-for-secrets
#    triggers:
#      - schedule:
#          cron: "0 1 * * *"