version: 2.1

orbs:
  secrethub: secrethub/cli@1.0.0

executors:
  base-agent:
    docker:
      - image: twdps/di-circleci-infra-image:stable

jobs:
  test:
    executor: base-agent
    steps:
      - checkout
      - run: bats test

  scan-repos-for-secrets:
    executor: base-agent
    steps:
      - checkout
      - run:
          name: scan-repos
          shell: secrethub run -- /bin/sh -eo pipefail
          command: ./scan_repos_for_secrets.sh poc-va-api poc-va-cli poc-platform-eks poc-platform-servicemesh poc-platform-vpc poc-iam-profiles poc-va-dev-portal-backstage poc-va-starter-service poc-va-starter-java

workflows:
  version: 2
  test:
    jobs:
      - test

  scan-repos-for-secrets:
    jobs:
      - scan-repos-for-secrets:
        context: dps-va-di
#    triggers:
#      - schedule:
#          cron: "0 1 * * *"