version: 2.1

executors:
  base-agent:
    docker:
      - image: twdps/di-circleci-infra-image:stable

jobs:
  test:
    executor: base-agent
    steps:
      - checkout
      - run: bats test

  scan-repos-for-secrets:
    executor: base-agent
    steps:
      - checkout
      - run: ./scan_repos_for_secrets.sh poc-va-api poc-va-cli poc-platform-eks poc-platform-servicemesh poc-platform-vpc poc-iam-profiles

workflows:
  version: 2
  test:
    jobs:
      - test

  scan-repos-for-secrets:
    jobs:
      - scan-repos-for-secrets
#    triggers:
#      - schedule:
#          cron: "0 1 * * *"